steps:
- name: '${_IMAGE}'
  args: ['npm', 'install']
  args: ['npm', 'run', 'jest']
  args: ['sonar-scanner', '-Dsonar.host.url=${_HOST}', '-Dsonar.login=${_LOGIN}', '-Dsonar.password=${_PASS}', '-Dsonar.sources=/workspace','-Dsonar.projectName=${_DEVOPS}-$BRANCH_NAME']

- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - 'deployment/devops-1'
  - 'nginx=gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
